### ISSUE TITLE
showDocument does not work

### ISSUE THREAD

**Issue by aliebhart** [sibvisions/flutter_jvx#100]
I have a button that calls:
getApplication().getLauncher().showDocument("xxx", null, "_blank");

That does not work in Flutter

**Comment by ToniHeiss** [comment]
The OS will try to launch the url. If it is a file you usually can pick a programm or just use the browser and download it yourself. I can't use a file picker as it is only an url, not a whole actual file to save.

**Comment by ToniHeiss** [comment]
When I use a url ending in pdf, even if it is a website, the phone suggested me the google drive pdf reader as an example. So it should be responsive to the kind of content the url links to.

**Comment by aliebhart** [comment]
I wanted to open another website, not open a document

**Comment by ToniHeiss** [comment]
if it is a standard url the OS will recognize it as such and only open the browser. My comment was aimed at @rjahn in regards to the support of downloading files.
