### ISSUE TITLE
You can not edit content in a table

### ISSUE THREAD

**Issue by aliebhart** [sibvisions/flutter_jvx#101]
In Flutter you can not edit the content in the table directly.
In React and Vaadin this is possible

**Comment by aliebhart** [comment]
or if this is intended, why is there a selection list icon ub tge tavke if you can't edit it there?

**Comment by rjahn** [comment]
It is possible with right mouse click… edit or double click/tap.

We had a bug with this feature but should work in one of thf next builds.

Flutter Web or native?

**Comment by aliebhart** [comment]
Toni said its already fixed as this was a bug with the new routing system.
