### ISSUE TITLE
Sort on header failed

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#105]
Components test screen -> Groups linked cell editor -> touch header

<img width="423" alt="image" src="https://user-images.githubusercontent.com/1307043/221995708-82ab771f-c08f-4069-8ed9-b476fe9705e1.png">

**Comment by ToniHeiss** [comment]
Sort should not be possible in there! Will fix

**Comment by rjahn** [comment]
Sort is possible in the popup -> I mean the server shouldn't have a problem.

**Comment by ToniHeiss** [comment]
Yeah, the server wont, but my UI does. This Table does not have the whole feature-set of a UITable. It is just the component to show the data. The server calls etc are in the wrapper of the table, which I can't use as this is the layouting component. This table only supports the callbacks that the header was clicked. I could implement it that the Linkedcelleditor sends the request. The design is not really up for it at the moment. There would be a lot of duplicated code. We could open a separate feature issue and deal with that later. At the moment it is not "cleanly" doable.

**Comment by rjahn** [comment]
ok, clear. A new issue would be good and a simple fix for this problem.
