### ISSUE TITLE
App overview locking mechanism

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#108]
Currently the app overview allows the locking of the config applications. This locks all applications to not be editable. When I have defined my own applications, these will still show, even with `"configsLocked": true'`. Should that be possible?

I think, if we lock down our configs, we should not show custom added applications, even locked.

e.g.

Config has the following:
```
"configsLocked": true,
"serverConfigs": [
  {
    "baseUrl": "",
    "appName": "demo",
    "username": "",
    "password": "",
  }
],
```

Should I theoretically see a self defined app called "myApp" when configsLocked is true? It does currently, it just locks it the same way it locks the predefined config applications.

**Comment by ToniHeiss** [comment]
For the following paragraph:
- Custom app: An app created by the user in the app overview or via a QR-Code
- Config app: A pre defined app by the config.json.

The following parameters exist in the config <parameter>(default if parameter does not exist):
"customAppsAllowed" (false) : If custom apps can be created, edited, deleted and started by the user. If false, then custom apps can only be deleted. Not started, not edited, not created. QR-Code scanner is hidden. (Dont auto delete to avoid confusing the user why all apps are now gone) -> Maybe explain why they can't be started when the user tries to start one that this app is configured to forbid them and the only reason we didn't delete them is so they can still save them somewhere before deleting them themselves. If this property is false, "clear apps" menu entry should still be visible if there still exists one custom app.

"serverConfigsLocked" (true): If config apps can be edited. If false, they can't be edited. Config apps can never be deleted or created by the user. 

"serverConfigsParametersHidden" (true): If the appname and the baseurl of config apps is hidden. Title is always visible. If this is true, then serverConfigsLocked is implicitely true!

The following parameters exist in the server configs:
"locked" (false) : same as serverConfigsLocked but only for this config app.
"parametersHidden" (false) : same as serverConfigsParametersHidden but only for this config app.

**Comment by Bungeefan** [comment]
Further notes:
`forceSingleAppMode` forces single app mode.

The "Manage single application" switch is hidden when either `customAppsAllowed` is false or `forceSingleAppMode`  is true.
