### ISSUE TITLE
Implement proper `requestTimeout`

### ISSUE THREAD

**Issue by Bungeefan** [sibvisions/flutter_jvx#109]
We should switch to the (now again maintained) famous DIO package as it supports a proper `requestTimeout` which should work fine even with long offline data requests.
This should even help us simplify our multipart request code.

Package: https://pub.dev/packages/dio

**Comment by rjahn** [comment]
Not sure if this package makes our client better?
web compatible?

**Comment by Bungeefan** [comment]
Our current client (the HttpClient from Flutter) is not really great to use for our feature requirements, and we had to implement a lot of features in a not really convenient way.
And yes, it's web compatible.
