### ISSUE TITLE
padding styles

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#119]
Please support:

f_padding_bottom_0 (none), f_padding_bottom_2 (half)
f_padding_top_0 (none), f_padding_top_2 (half)
f_padding_left_0
f_padding_right_0

for label and text inputs - as good as possible.

Labels shouldn't be a problem..

left, right -> if it makes sense?

**Comment by ToniHeiss** [comment]
We don't have left or right paddings, those won't be implemented for now.
