### ISSUE TITLE
Error view without exceptions/details

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#125]
Our message.error already sends details and exceptions...

Do we support such error responses without details and exceptions also?

If server doesn't send details and/or exceptions - the client should work without problems and without details!

**Comment by rjahn** [comment]
OK, the properties are:

details - a string
exceptions - an array of ErrorRecords (message, exception - both strings)

both are nullable

No changes for title and message.
No message -> you should show the error but with a placeholder message?

**Comment by ToniHeiss** [comment]
>No message -> you should show the error but with a placeholder message?

Seems good.
Any plan for us to implement showing the exceptions/details or is ignoring it, as we currently do, ok?
