### ISSUE TITLE
Unable to load asset: "packages/khodrah_clean_arc/assets/images/base_images/splash.png".

### ISSUE THREAD

**Issue by mazab99** [sibvisions/flutter_jvx#127]
static String getPackageName() {
    return "my_package_name";
  }

 I tried to use image.asset but nothing happen
The asset does not exist or has empty data.

**Comment by rjahn** [comment]
Do you have a demo project?

**Comment by rjahn** [comment]
I guess you did something wrong here?

It's not necessary to change the core project because it also works as library.
Simply check our example: https://github.com/sibvisions/flutter_jvx.example

**Comment by rjahn** [comment]
No Input, no interaction - no help.

**Comment by mazab99** [comment]
I don't use the package 
I just take the file of image loader

**Comment by rjahn** [comment]
Demo project? Did you try the example?

**Comment by rjahn** [comment]
Simply post your whole example, because we don't know what's your use case.
Image loading is no problem in the whole project, so we guess you do something different/unexpected.
