### ISSUE TITLE
Improve "invalid server version" message

### ISSUE THREAD

**Issue by Bungeefan** [sibvisions/flutter_jvx#131]
Currently the message for the mismatch is hardcoded to "the server is too old", which is not always the case, therefore we should make the message dynamic.

**Comment by Bungeefan** [comment]
@rjahn @ToniHeiss 
Please provide feedback:

![grafik](https://user-images.githubusercontent.com/39010966/232801499-57d72f88-af4b-416e-95d7-debc97f0963c.png)

**Comment by rjahn** [comment]
Compatibility issue

This client is not compatible with server!
Client: x.x.x ! Server: y.y.y

Retry can be removed from this dialog because it won't fix the problem.
Edit Apps should be replaced with an OK

**Comment by ToniHeiss** [comment]
"The server and client are not compatible" makes it a bit of a more general info. The client not beeing compatible with the server makes it seem like the error lies on the client-side.

**Comment by Bungeefan** [comment]
New iteration, how about this?

**Comment by rjahn** [comment]
The unequal sign is not right because version number can be different!

The client and server version are incompatible.
<br>
Client: x.x.x <-> Server: y.y.y
