### ISSUE TITLE
Update default Log Levels and add as config option

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#134]
Default log setting logs many things? Not sure if this slows down the application a little bit?

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/1307043/234483412-0d46f498-3c23-4d89-abce-61959ea68815.png">

Is there a loglevel or something to configure?

**Comment by ToniHeiss** [comment]
You can configure the log level only via the code. In the class "FlutterUI" are statically defined logged with their respective log level. There you can change them. We should make them somewhat accessible in the near future.

**Comment by rjahn** [comment]
OK, but the config should be different in dev and prod mode!

**Comment by ToniHeiss** [comment]
Only the default logger is set to two different levels depending on the mode. The rest always logs on info. In prod we should probably go down to warnings.

**Comment by rjahn** [comment]
or error?

**Comment by ToniHeiss** [comment]
We could. But if we integrate some kind of files log or remote log for future users, we should stay on warning level so we can potentially see errors coming and how they formed, instead of just reacting to the errors themselves.

**Comment by rjahn** [comment]
WARN is better than INFO right now

**Comment by Bungeefan** [comment]
We should add the option to customize log levels via config.
