### ISSUE TITLE
Table & LinkedCellEditor style f_no_alternating_row_color 

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#141]
f_no_odd_even should disable the alternating colors of the table. The same goes for the linked cell editor.

**Comment by ToniHeiss** [comment]
f_no_alternating_row_color -> more readable what it does

**Comment by rjahn** [comment]
no, not fixed

**Comment by ToniHeiss** [comment]
Are editor styles applied to the cell editors? Do i have to explicitely give the LinkedCellEditor the style or should it be enough to give the editor the style? Currently i only read out styles that are sent in the celleditor json.

**Comment by rjahn** [comment]
The editor doesn't forward the style automatically. The cell editor has a style and the editor has a style.

If you set the linked cell editor a specific style, it will use the style in table and editor edits. If you set the style only for an editor, you can fall-back in your linked cell editor if you want?

**Comment by ToniHeiss** [comment]
I just think for a citizen developer it might be easier to set these styles to the editor, instead of creating a UILinkedCellEditor by hand.

**Comment by rjahn** [comment]
You could check the style of cell editor and if not found, check editor style as well. But if a citizen developer only sets the editor style, it won't work in direct table edits.
