### ISSUE TITLE
style for no_clear button 

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#142]
Would be great to have:

f_no_clear

style for (cell)editors. Sometimes we deny clear and reset the value automatically. In this case, the X button "does nothing" so we could hide it. Reset is event driven, so there's not general rule when the X should be hidden. Best is a custom style.

**Comment by rjahn** [comment]
If f_no_clear is set for a column with a linked cell editor (e.g. Filter Editor with linked cell editor), we also should remove No value option from popup.

We already remove the option in case of mandatory columns. But in case of a Filter editor, the column is not mandatory. In this specific case we should have the option to remove the No value button from the popup.

Better ideas?

**Comment by ToniHeiss** [comment]
Is implemented. Date, Time and Linked don't have a clear if not nullable or if f_no_clear is set

TableEditDialog works too!

**Comment by rjahn** [comment]
Do you check the style of editors as fall-back as well?

**Comment by ToniHeiss** [comment]
Yes, that works too.
