### ISSUE TITLE
Investigate `beamBack` after user closes screen

### ISSUE THREAD

**Issue by Bungeefan** [sibvisions/flutter_jvx#145]
Bug Tracker for #144

> There seems to be a weird bug that needs further researching, which blocks us from closing the current screen via the close button in the sidebar on mobile.
> 
> Having for example "First" open and then opening "Second" and finally trying to close "Second" via the Sidebar Menu.
Even though we are correctly routing and rebuilding the new (old) screen, Flutter still shows the now old WorkScreen on top of the new one, which shouldn't even be possible.
Still unclear if it's "our" bug, on the behalf of the Beamer package or Flutter itself.

**Comment by Bungeefan** [comment]
Failed workarounds:
* `maybePop`/`pop` instead of `beamBack`: throws other errors (would be fixable) but doesn't change behavior.
* delayed `beamBack`: even with 5s delay, no difference.

**Comment by Bungeefan** [comment]
Found the culprit:
A Drawer or EndDrawer in a Scaffold consumes a pop request, which is totally fine, but navigator then fails to update the UI correctly to show the possible new pages it was provided.

Workaround:
Close EndDrawer before routing.

Found multiple issues that seem to have the same culprit as our bug:
* https://github.com/flutter/flutter/issues/82437
* https://github.com/flutter/flutter/issues/107804
* https://github.com/flutter/flutter/issues/118645

Conclusion: Flutter Navigator Issue, Beamer is fine, as this also happens with the Flutter native routing package (go_router).

**Comment by rjahn** [comment]
Cool finding! Thumbs up.
