### ISSUE TITLE
coloring not right

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#146]
![image](https://github.com/sibvisions/flutter_jvx/assets/1307043/db485c2b-be97-4e37-b1a4-eea02c7117b9)

top: 1px white - background height wrong?

**Comment by ToniHeiss** [comment]
[Code of Background](https://github.com/sibvisions/flutter_jvx/blob/c4d4481354f2a03c9dc38dbba7a06a24efdb9414/lib/src/components/panel/fl_panel_widget.dart#L43) 


The panel (which I guess it is from the look of the TAG Editor?) has no calculation for the height of the background coloring. It is just set on the container that represents the panel. More likely to be a clipping issue created by the border container or the cliprreact inside.
