### ISSUE TITLE
wrong height

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#147]
![image](https://github.com/sibvisions/flutter_jvx/assets/1307043/1e6b69dd-ce58-45e1-9d4d-718e84aea0c1)

A panel with text in it has a different default height than an editor?

**Comment by ToniHeiss** [comment]
![grafik](https://github.com/sibvisions/flutter_jvx/assets/72435900/890208b4-4b58-4848-ab65-4a92df62f211)
I forcefully removed the margins for a test and the insets of the border. Now the TagEditor is the same height as a textfield (48px), but the material effects of the button are painting over the border.
