### ISSUE TITLE
html editor support

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#154]
https://pub.dev/packages/html_editor_enhanced

Should be possible to use this for our html editor?

**Comment by ToniHeiss** [comment]
Will look into that, looks promising.

**Comment by ToniHeiss** [comment]
Am currently trying to integrate the package into our framework. It did look promising, but I am still unsure if this package is going to work in our current situation. 

Also testing: https://pub.dev/packages/quill_html_editor
