### ISSUE TITLE
Element identification

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#159]
We should be able to switch the application to something like a "design" mode. This mode should be enabled by server via startup. If not enbled -> no chance to use this feature.

The client should show an icon or a button to switch to design mode (best place, top bar/menu). Button should en/disable design mode. 

Feature: click or maybe only long-press -  on an element and show it selected (round rectangle, transparent color). Send a request to the server with name.

Use-case: Change the screen on-demand. 

* select a table -> show/hide columns
* select an editor -> move editor down/up
* select an editor -> add a new column to the table

We need to know "where we are" to change the screen.

**Comment by ToniHeiss** [comment]
Only sending the request and what kind of request is open, rest is implemented

**Comment by rjahn** [comment]
You should support a simple API for this feature, because it's included in this project, but we will use it in a different project.

**Comment by ToniHeiss** [comment]
You can currently listen to the server sending yes/no if it is allowed to activate the design mode.
You can listen to the switch of on/off of the design mode itself.
You can also listen to the elements that are selected and when they are selected. So theoretically you can add listeners to all these 3 events. 

Any more needed?

**Comment by rjahn** [comment]
We need a feature to hide selection and design mode programmatically.

**Comment by ToniHeiss** [comment]
Hide selection is just disabling the active design mode or selecting null.
The ability to hide the design mode button is also possible. 

I will implement a way to deactivate it permanently so that the server can't "allow" it via startup. Currently hiding is possible but will get overruled on the next startup again.

**Comment by ToniHeiss** [comment]
Overruling of application parameters now possible via `AppManager`, therefore design mode can be hidden/shown on demand and the server setting can be overruled before it is activated.
