### ISSUE TITLE
Hyperlink widget

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#161]
Currently our Hyperlink widget is a button.

With latest version, Hyperlink implementation will send url and target properties as well. We can create a real hyperlink component instead a fake link!

So, if you receive an url and optional target property, use a real hyperlink instead of a button!

In Safari, the popup will be blocked if you use a button. In Chrome and Firefox, this is working!

**Comment by rjahn** [comment]
Keep sending the pressed event. This is a nice thing for the application.

**Comment by rjahn** [comment]
The hyperlink action event won't send you a showDocument with latest update.

**Comment by ToniHeiss** [comment]
Isn't this a react bug? I don't see how there is a difference between a button and a label that is clickable?

**Comment by ToniHeiss** [comment]
I will test this on the mac in safari, but I doubt it will be an issue. Flutter does not use real html as far as I know. It is a canvas.

**Comment by rjahn** [comment]
You're right. How does flutter handle popups or links to other sites?

**Comment by ToniHeiss** [comment]
```dart
launchUrl(
      Uri.parse(url),
      mode: LaunchMode.externalApplication,
    );
```

I just launch the url.

Testing on mac in safari seems to work. Tested the Button in the Components screen of the demo application.

We don't use the targets though. So we don't differenciate between new tab/same tab as we streamlined it to always be a new tab. (Because mobile does too, as it isn't a browser)

Should we implement the targets for web?

**Comment by rjahn** [comment]
target is not relevant for mobil... should be outside
in browser, we could support both

**Comment by ToniHeiss** [comment]
>How does flutter handle popups or links to other sites?

https://pub.dev/packages/url_launcher

It is a package we use to launch urls which then uses the respective platform implementations.

> https://github.com/flutter/packages/tree/main/packages/url_launcher

There are all the relevant platform implementations
