### ISSUE TITLE
Barcode - Support for QR-Code Scanner

### ISSUE THREAD

**Issue by ThauAngelo** [sibvisions/flutter_jvx#168]
Seperate Barcode - Scanner, or better integrated into existing QR-Code Scanner.

**Comment by ToniHeiss** [comment]
![grafik](https://github.com/sibvisions/flutter_jvx/assets/72435900/8176074b-2e72-437f-8d60-e2d2f0b74cf9)

Testcode: 012345

**Comment by ThauAngelo** [comment]
![image](https://github.com/sibvisions/flutter_jvx/assets/104762824/3e2d8b97-389f-4f71-8304-350f21da345a)

**Comment by rjahn** [comment]
A Datamatrix is not a Barcode. But we'll see what's possible.

**Comment by Bungeefan** [comment]
Scanner should now support all available formats, implemented in 10eeb9869efd0163b4cda374077594f1d710012f
