### ISSUE TITLE
Support clearColumnNames of LinkedCellEditor

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#172]
not the same as https://github.com/sibvisions/flutter_jvx/issues/171

LinkedCellEditor has property: clearColumnNames

clearColumnNames will be cleared before applying the entered value, but only if the value is not available in the dropdown list (works with null  value or custom value if validation is disabled)

Currently, we don't support linked cell editors with disabled validation. 

But we support setting null. 
Above rule should work: if the value is not available in the dropdown list -> set clearColumnNames to null

**Comment by ToniHeiss** [comment]
closed by: ed183b65b
