### ISSUE TITLE
Hide specific settings

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#175]
It should be possible to hide some settings like:

Language
Design

-> via config

An app user shouldn't be able to change hidden settings.

It should be possible to set the design mode via mobile.xml property.

We already send client properties, so simply add following in mobile.xml:

<parameters>
  <Mobile.client.designSetting>dark|light|system</Mobile.client.designSetting>
</parameters>

**Comment by rjahn** [comment]
designMode is already reserved!

**Comment by Bungeefan** [comment]
How about `themeMode` as in Flutter?

**Comment by rjahn** [comment]
mobile_style.xml ->

  <theme>
    
    
  </theme>
