### ISSUE TITLE
Editor - Text - x not touchable

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#199]
I have an UIEditor which edits a text column and the value is set. The small x is shown.
It's not possible to touch the x until the editor has the focus.

Same works without problems for linked cell editors, number cell editors.

**Comment by ToniHeiss** [comment]
Demo and a new app did not result in any reproduction. Tested with UIEditor multiline, single line and password. Will try next with TextArea and TextField and then with a generated screen.

**Comment by ToniHeiss** [comment]
https://github.com/sibvisions/flutter_jvx/assets/72435900/48115fdd-1255-4df4-af20-09f102004b3a

Will look further
