### ISSUE TITLE
readonly checker support

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#206]
FetchResponse has a new property: 

```
"recordReadOnly" : {
  "records" : [ [ 1, 1, 0 ], [ 0 ], [ 1, 1, 0 ], [ 1 ], [ 1, 1, 0 ] ]
}
```

1 = editable
0 = readonly

The elements are in the same order as the columnNames.
If the number of elements is smaller than the number of columns -> repeat last number:

```
[0, 2, 0, 1, 1, 1] => [0, 2, 0, 1]
[0, 0, 0, 0] => [0]
[1, 1, 1, 1] => [1]
```

A test screen is available: **ReadOnly Checker** -> features user.

**Comment by ToniHeiss** [comment]
[bc74046](https://github.com/sibvisions/flutter_jvx/commit/bc74046b6cb394ead20f2dd9c7de4fcab30f880b)
