### ISSUE TITLE
Use layoutMode in web environment

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#47]
The layoutMode (Mini, Small, Full) is available as response of /deviceStatus request. 

Mini: No sidebar
Small: Small sidebar width (only icon and some characters - fade out text)
Full: Full sidebar width (icon and all characters)

Currently, we don't use the layoutMode.

**Comment by Bungeefan** [comment]
ff754caa47282982a0ea352ad56acc75847a5d2d

**Comment by Bungeefan** [comment]
Implemented with ff754caa47282982a0ea352ad56acc75847a5d2d
