### ISSUE TITLE
SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 53334

### ISSUE THREAD

**Issue by mazab99** [sibvisions/flutter_jvx#48]
Failed to send startup
Error processing StartupCommand-chain
Error while sending ApiStartUpRequest

**Comment by ToniHeiss** [comment]
To what Server are you trying to connect? Is your app configured?

**Comment by mazab99** [comment]
iam from  Egypt , does it will work ?

**Comment by mazab99** [comment]
I just need to discover it and increase my knowledge ,

**Comment by ToniHeiss** [comment]
https://github.com/sibvisions/flutter_jvx.example

**Comment by ToniHeiss** [comment]
Read our read me.

**Comment by mazab99** [comment]
ok I will try using example app , but the main app will not work with me ?

**Comment by ToniHeiss** [comment]
It wont as you have to have a JVx Server, as this is only a front-end technology addition for JVx.

**Comment by ToniHeiss** [comment]
As stated in the readme:

Requirements

    [Flutter dev environment](https://flutter.dev/docs/get-started/install)
    Java 8 or later (for the JVx application)
    **A JVx application, running on a Java application (Jetty, Tomcat, ...) server, using [JVx mobile UI](https://sourceforge.net/projects/jvxmobile/)**

**Comment by mazab99** [comment]
do you mean I should put this in my yaml ?

**Comment by rjahn** [comment]
You could use the demo application for tests. Simply use the base URL: `https://cloud.sibvisions.com/previewer/services/mobile`

and the application name: `Previewer`
