### ISSUE TITLE
SetValuesCommand/SetValuesRequest has additional property "columnName"

### ISSUE THREAD

**Issue by mhandsteiner** [sibvisions/flutter_jvx#50]
The SetValuesCommand has an additional property columnName in future. If not sent, server behaviour does not change.
If columnName is sent, the server will additionally check, if the specific column is read only, and will open an Error View.
The columnName is the column, that is edited (caused the SetValuesCommand).

**Comment by rjahn** [comment]
The property is now renamed to editorColumnName

**Comment by ToniHeiss** [comment]
What if a LinkedCellEditor changes 2 columns? Which column should be named. The primary column of the editor or both edited columns?

**Comment by rjahn** [comment]
The bound column.... every editor has 1 column.
