### ISSUE TITLE
Checkbox cell editor not working

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#55]
If you use a simple Checkbox cell editor with value null or Boolean.FALSE, it's not possible to toggle values.

null should be handled as Boolean.FALSE

**Comment by ToniHeiss** [comment]
Checkbox does not work in swing either.

Checkbox sends null as selectedValue and null as deselected value. Thats the reason why my checkbox always sends the deselected value => null, as _value == selectedValue is true.

**Comment by ToniHeiss** [comment]
Not a bug
