### ISSUE TITLE
Offline Mode can not be initialized because of SQLite bug in Android 10

### ISSUE THREAD

**Issue by tschoenberger1203** [sibvisions/flutter_jvx#60]
When starting the offline mode with Android 10 a SQLite Bug(https://sqlite.org/src/info/86ba67afafded936) is triggered because during insert the check constraints for precision and scale are checked before the values are properly adjusted

**Comment by Bungeefan** [comment]
797b6e29045004cec92dd1ac7ec342d91099cfd7 adds a config property which disables the `CHECK` constraints.
