### ISSUE TITLE
Server connection lost message temporary

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#64]
Server connection lost message is not visible as long as connection is lost. It's only a temporary message?
A transparent background would look better than gray

**Comment by Bungeefan** [comment]
Yes, it's temporary because there is currently no way to detect when the web socket successfully reconnected, until we receive a message from the server.
Since, to my knowledge, there is currently no guarantee that will happen any time soon after the connection is established, therefore a persistent user banner (SnackBar) could be wrong/misleading.

Tracking issue from package: https://github.com/dart-lang/web_socket_channel/issues/25

**Comment by rjahn** [comment]
Simply show the message if an error occurs... and remove the message if no error occurs?

**Comment by Bungeefan** [comment]
No, there is no such easy state.

There is no definitive point in time where we could conclude that there won't be a connection error, the only callback we have is when there was ANY error while reading the stream, this can be an error on the initial connection but can also occur in the middle of the connection (e.g. Wi-Fi disconnects).

However, the issue mentioned above adds both a timeout parameter (at least for the mobile version) and a ready field.

**Comment by rjahn** [comment]
Still not clear, if you detect a connection error -> show the message. A retry is already implemented? so if you establish a connection remove the connection error message?

If you don't know if connection is usable -> send an alive as test?

**Comment by Bungeefan** [comment]
As said above, there is no point where we would know "this web socket is now usable".
So when would we send the "alive" command then?
Just periodically until we either receive a stream error (which isn't guaranteed to ever come) or it works?
And as there is no timeout, when would we stop with this?

If we can't/don't want to wait for the above issue, the server could send us a "SUCCESS" message, which we could use to identify a connected state.

**Comment by rjahn** [comment]
Server now supports a new request parameter: confirmOpen (like clientId, reconnect). If parameter is available -> web socket open sends OPEN_OK

The parameter is necessary for backwards compatibility.
