### ISSUE TITLE
API/User documentation

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#66]
We need documentation for API, offline API, replace components, custom components, custom login, stlying, ... The example application (https://github.com/sibvisions/flutter_jvx.example) is a good start and should be used for additional examples.

We could use https://github.com/sibvisions/reactUI.example and https://github.com/sibvisions/reactUI as templates for our flutter UI documentation.

**Comment by ToniHeiss** [comment]
Further improvements to the documentation will be handled by separate Tickets.
