### ISSUE TITLE
Timeout configuration (web)

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#67]
assets/config -> a config file for general settings like timeout (like in reactUI)

**Comment by Bungeefan** [comment]
As far as I could research, it is not supported to add assets after the build.
However, I was successful by just adding the file under the web assets folder and it worked.

I added the following file under `build/web/assets/assets/config/`:
_Note: The config folder is missing in the previewer._
`app.conf.json`:
```json
{
  "requestTimeout": 5
}
```

**Tested with:**
`flutter build web --release && python3 -m http.server --directory build/web/`
Placed file.
Reloaded with `CTRL+F5`.
The new file is loaded by the browser and being applied on-top the constructor config.

**Conclusion:**
It works fine this way, but I could break whenever Flutter decides to change their asset loading process, as this is not supported.

**Comment by Bungeefan** [comment]
**Alternative "workaround":**
Add an empty `app.conf.json` file to the build, which can be edited later.

**Comment by rjahn** [comment]
Our client already recognizes loading the app.conf.json file? right? Usually, the pubscpec.yaml contains:

> assets/config/

If there's no app.conf.json, at build time, it's not possible to access the file?

Your description is not clear for me, because the asset mapping is currently by directory and not by file. So If flutter will change asset loading, we have other problems as well?

Following scenarios:

1) The app.conf.json is not available... but after deployment we need it, so we create it manually...
2) The app.conf.json is available and empty (or contains disabled properties.. comments) -> we simply change the file after deployment


The second scenario should work without problems, right?
The first scenario? What will happen if we add the asset by name to the yaml file? A build error if asset is not available?

**Comment by Bungeefan** [comment]
It seems like the `flutter.assets` config in **pubspec.yaml** doesn't impact us in any way for this issue.

Even though there is no `config/` in the pubspec during build, the HTTP request for the file in the subfolder is still made by the browser.
This is the part where Flutter could decide to change this behavior to first assess the generated `AssetsManifest.json` file which contains a list of all known assets and then fire the request depending on that file.

Example:
In the previewer there is currently only this set in the config:
```yaml
  assets:
    - assets/
```
Nevertheless, I can still add the new `config` folder after the build, and it works (for now).

If Flutter ever decides to change this, this should be the only instance that can break, as our other approaches to asset loading are supported.

Regarding your mentioned scenarios:

1. Yes, declaring a non-existent file in the `assets` section makes the build fail.
2. Currently? Yes, and I also believe that this will work reliably in the future, although assets are defined as static never-changing files, I don't think that there will be ever a change that would prevent editing the file after the build.

**Comment by rjahn** [comment]
The assets are only important for the build.
I guess flutter won't change resource loading because it makes old applications incompatible and it's not important for flutter. Why shouldn't the application dynamically load resources?

Anyway, if we add the file manually after build, it will work.

An empty file is not nice because it's an unused resource.... but a 404 for a not found resource is also not nice...

No perfect solution possible, we should use it as it is.
