### ISSUE TITLE
Use h-align for group panel

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#73]
Use horizontalAlignment for header position of group panel.

Currently, the text is always centered.

**Comment by ToniHeiss** [comment]
>Currently, the text is always centered.

Only in the mobile frame, in the web frame it is left aligned.

I will implement it for the web frame first and for the mobile frame if we've discussed it.

**Comment by rjahn** [comment]
No discussion necessary...
If user defines alignment -> simply align it.

Or is there a problem with alignment?
Default setting should be centered, if server doesn't send h-align.

**Comment by rjahn** [comment]
Is there a difference between web and mobileOnly?

**Comment by ToniHeiss** [comment]
Yes.

The web places the header to the left, the mobile version centers it.

**Comment by rjahn** [comment]
Perfect!
