### ISSUE TITLE
Table editable

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#78]
The table widget should only be editable if:
Model is editable, enabled and meta data allows updates.

Table cell editors are inside the table if they are direct cell editors. Cell editors which are not in the table are editable via double or single click, depending on which preferred editor mode is sent, and opening a dialog with an editor inside.

Linked and date celleditors will have a direct delete button inside the table if their preferred editor mode is single click. These cell editors open their respective selection popup dialog directly, with no editor dialog in-between. 

Table can be editable through a long press menu entry called "Row edit", which opens a dialog to edit the whole row. Cell formats are not applied to these cells. Mandatory colors are applied. Editing a cell in the row edit should not send standalone set values commands. All value changes will be sent by one unifying set value command.

**Comment by rjahn** [comment]
don't forget to recognize direct cell editor property -> checkbox, choice

**Comment by ToniHeiss** [comment]
All variants of all cell editors need to be tested now with e.g.

Table needs the following comprehensive tests:
- [ ] Update disabled
- [ ] Insert disabled
- [ ] Delete disabled
- [ ] Read only
- [ ] Focusable
- [ ] Refresh
- [ ] After row selected - update/insert/delete - disabled
- [ ] Error after row selected
- [ ] Dialog close on changes
