### ISSUE TITLE
textfield icons via style

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#85]
Would be great to have textfield icon styles like:

https://design.gs.com/input-icon-variations.png
https://media.geeksforgeeks.org/wp-content/uploads/20210327231910/materialdesigntextinputfieldgfg-588x660.jpg
https://static.vecteezy.com/system/resources/thumbnails/004/141/447/small/search-bar-horizontal-linear-border-with-text-input-field-magnifying-glass-icon-in-frame-simple-flat-searching-button-design-for-seo-networking-technology-web-ui-internet-navigation-web-browser-free-vector.jpg
https://assets.justinmind.com/wp-content/uploads/2019/04/web-form-design-validation.png

We could use styles:

f_textfield_lefticon_<name>
f_textfield_righticon_<name>
e.g. f_textfield_righticon_address, f_textfield_righticon_search

The name could be a fonticon name/constant?

f_textfield_valid (also changes border color)
f_textfield_error (also changes border color)
f_textfield_warning (also changes border color)
f_textfield_info (also changes border color)

With this feature, we could remove some label e.g. Search

**Comment by ToniHeiss** [comment]
{} => mandatory
[] => optional, can be cut out -> dont add the "_" before or after either!

Icon syntax:
f_icon_{prefix/suffix}_{FontAwesome.}{iconName}_{ColorInHex}_[OptionalColorForDarkMode]

Examples:
f_icon_prefix_search_#ff0000
f_icon_suffix_FontAwesome.search_#ff0000_#ff00ff

Bordersyntax:
f_border_[focused]_color_{ColorInHex}_[ColorForDarkMode]

If no colors for the dark mode are specifically set, uses the normal color.

**Comment by rjahn** [comment]
please post a list of valid icon names

**Comment by rjahn** [comment]
color should be optional anf dhould start with # I guess

**Comment by ToniHeiss** [comment]
It already is, i just posted it wrong.

**Comment by ToniHeiss** [comment]
> please post a list of valid icon names

https://github.com/sibvisions/flutter_jvx/blob/main/lib/src/util/font_awesome_util.dart

Every string in the map "ICONS" is possible. With or without "FontAwesome."
