### ISSUE TITLE
Global font

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#88]
Use a specific default font to not have the issue of every device having a different font.

**Comment by rjahn** [comment]
Current test... Padding is not good, but Label and Editor text have the same baseline!

![padding](https://user-images.githubusercontent.com/1307043/216438353-a68bc6ca-3e0d-4103-94d6-2166ab7e7e8d.png)

**Comment by ToniHeiss** [comment]
Implemented padding calculation instead of a global font
