### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#90]
Would be great after successful login

Would be great for buttons (optional via f_haptic_1, f_haptic_2, ...).

Maybe useful in some other situations?

**Comment by Bungeefan** [comment]
Added the following styles to buttons:
* `f_haptic_light`: Provides a haptic feedback corresponding a collision impact with a light mass.
* `f_haptic_medium`: Provides a haptic feedback corresponding a collision impact with a medium mass.
* `f_haptic_heavy`: Provides a haptic feedback corresponding a collision impact with a heavy mass.
* `f_haptic_click`: Provides a haptic feedback indication selection changing through discrete values.
* `f_haptic`: Provides vibration haptic feedback to the user for a short duration.
