### ISSUE TITLE
Signature with lockMode

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#92]
Signature component now has a property: lockMode (boolean)

If lockMode is enabled, a small lock should appear and editing is only possible if "unlocked". If value is confirmed -> auto-lock.

This should temporary disable changing value to allow scrolling.

**Comment by ToniHeiss** [comment]
The following 2 properties have been added:

editLock -> On the bottom right corner is an edit button. This button must be pressed to allow editing.
Once editing is allowed: X button resets the painting, OK (✔️) button confirms and locks again afterwards. If you dont want to confirm but want to disable painting again -> press x to clear then OK to confirm nothing.  
saveLock -> If true, shows an open lock on the top left corner to show saveLock is active but not yet locked. Signature pad behaves the same. Once a value has been set, the lock is closed and no editing is possible. All edit buttons, even the editLock button, is hidden.
