### ISSUE TITLE
deviceId

### ISSUE THREAD

**Issue by rjahn** [sibvisions/flutter_jvx#95]
If no unique device id is available for a device (mobile only), just create a UUID and save it as long as the app is installed.
This is not a deviceId, more or less an appId for the installation. 

We can use this to identify the installation.

iOS has a deviceId... should?

**Comment by Bungeefan** [comment]
iOS uses `identifierForVendor`.
https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor

Android uses `ANDROID_ID`.
https://pub.dev/packages/android_id
https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID
Example:
```json
"deviceId":"3a20f5cb5fa0a318"
```
